### PR TITLE
2575 raspberry pi os logo

### PR DESCRIPTION
**Pull request by cybershoe**
Added logic in OS detection to check for the Raspberry Pi OS repository that differentiates it from vanilla Debian.

### CODE REVIEW

**Comment by cybershoe** [comment]
Fixes #2575

**Comment by romkatv** [comment]
What is the output of the following command on your Raspberry Pi?

```
cat /etc/os-release
```

Which OS have you installed on your Raspberry Pi and how?

**Comment by cybershoe** [comment]
```❯ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"```

OS is Raspberry Pi OS Lite (64-bit), imaged directly to the SSD with Raspberry Pi Imager v 1.85. Recent versions of Raspberry Pi OS don't change `os-release`, but you can detect that it's the Pi version of Debian by looking for the pi-specific repositories in `/etc/apt/sources.list.d/raspi.list`

**Comment by romkatv** [comment]
Thanks for the additional details. Merged.

**Pull request merged**
