### PR TITLE
Option to show/hide virtualenv name

### PR DESCRIPTION
**Pull request by WhoMeNope**
Add an option to show/hide virtualenv name.

Adds `POWERLEVEL9K_VIRTUALENV_SHOW_ENV_NAME` for the `virtualenv` segment.

### CODE REVIEW

**Comment by romkatv** [comment]
What are you trying to achieve?

- Are you trying to display just the python version in prompt? Basically, `python --version`.
- Are you trying to display a python logo in prompt unconditionally even if you don't have a virtual environment activated and even if you don't have Python installed?

**Comment by WhoMeNope** [comment]
I'm trying to show just the python version and only for virtualenvs.

By default the `virtualenv` segment was showing the name of the virtualenv (which is basically just the directory name) and optionally a version.
I have a couple of directories with very long names, and this was making the prompt too long.

**Comment by romkatv** [comment]
> I'm trying to show just the python version and only for virtualenvs.

That's not what the code does though? If you set `POWERLEVEL9K_VIRTUALENV_SHOW_ENV_NAME=false`, it'll always display Python version.

> By default the `virtualenv` segment was showing the name of the virtualenv (which is basically just the directory name) and optionally a version.
> I have a couple of directories with very long names, and this was making the prompt too long.

Does this do what you want?

```zsh
typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=true
typeset -g POWERLEVEL9K_VIRTUALENV_CONTENT_EXPANSION='${P9K_CONTENT%% *}'
```

**Comment by WhoMeNope** [comment]
> That's not what the code does though? If you set `POWERLEVEL9K_VIRTUALENV_SHOW_ENV_NAME=false`, it'll always display Python version.

I'm running it right now and it does exactly what I've wanted. Showing only the python version and only if a virtualenv is active.

> Does this do what you want?
> 
> ```shell
> typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=true
> typeset -g POWERLEVEL9K_VIRTUALENV_CONTENT_EXPANSION='${P9K_CONTENT%% *}'
> ```

That also works. 

Both show the same thing.

But having a simple option to show/hide the name would be nice; since the option for hiding version is already there.

**Comment by romkatv** [comment]
> I'm running it right now and it does exactly what I've wanted. Showing only the python version and only if a virtualenv is active.

You are right. `_p9k_prompt_virtualenv_init` does that.

> But having a simple option to show/hide the name would be nice; since the option for hiding version is already there.

If the existing parameter allows you to get what you need, there is no reason to add another parameter. It may seem easier to set a parameter to `false` but everyone's idea of a simple boolean parameter is different. Someone later will ask for a parameter to swap Python version and the name of virtual env around. Another person will ask to hide virtual env when python version is 3.x. Yet some other person will ask to truncate virtual env name to the first 12 characters. All these use cases, and may like them, can be satisfied with the existing parameters. Adding a parameter for each will create so many parameters that no one will be able to find the one they need.

**Comment by WhoMeNope** [comment]
Fair enough.

But then `POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION` should not exist either.

**Comment by romkatv** [comment]
You are right, if that parameter didn't exist today, it wouldn't be added. It does already exist thought. Powerlevel10k doesn't break user configs, so the parameter cannot be deleted.

**Pull request closed without merging**
