### PR TITLE
Update powerlevel10k.zsh-theme

### PR DESCRIPTION
**Pull request by grigorii-horos**
Detect $0 according to the standard:
https://zdharma-continuum.github.io/Zsh-100-Commits-Club/Zsh-Plugin-Standard.html

### CODE REVIEW

**Comment by romkatv** [comment]
I don't think this document is a standard in any conventional sense.

What are you trying to achieve with this change?

**Comment by grigorii-horos** [comment]
Usually, you can detect base folder using this code `${(%):-%x}:A:h}`, but you cannot detect the root folder for eval <<'script', and for some other rare cases. In [zpm](https://github.com/zpm-zsh/zpm) I have all plugin source code in one big file that located in cache directory, so I have error in detection of $0

**Comment by romkatv** [comment]
Does setting `POWERLEVEL9K_INSTALLATION_DIR` help?

**Comment by grigorii-horos** [comment]
Theoretically, everyone can set up this variable, but I think will be better to detect $0 in properly way.

**Comment by romkatv** [comment]
> I think will be better to detect $0 in properly way.

I agree with this. We just seem to disagree on what's proper. I think using `eval` instead of `source` is not proper. Do you have a reason to do that?

**Comment by grigorii-horos** [comment]
`eval` just an example. I don't use this approach. In case of `zpm` we have another case: e have source code in one dir, but some required files in another directory.

**Comment by romkatv** [comment]
Why? What problem are you trying to solve? Can you instead source powerlevel10k as it says in the docs?

**Comment by zfben** [comment]
Does standardized $0 handling will make the plugin more complex or bugs? If not, I guess it's nice to have.

**Comment by romkatv** [comment]
I don't add code that serves no purpose.

**Comment by romkatv** [comment]
Closing due to inactivity. If you discover a need for this hack, please send another PR or reopen this one.

**Pull request closed without merging**
