### PR TITLE
fix instruction for installation with oh-my-zsh

### PR DESCRIPTION
**Pull request by junaid-ali**
the ZSH_THEME variable should be added before `source $ZSH/oh-my-zsh.sh`

### CODE REVIEW

**Comment by romkatv** [comment]
If you are using Oh My Zsh, `ZSH_THEME` is where it should be.

**Comment by junaid-ali** [comment]
> If you are using Oh My Zsh, `ZSH_THEME` is where it should be.

@romkatv I tested a fresh install of both oh-my-zsh and powerlevel10k on two machines, and on both I had to put the `ZSH_THEME` before `source ...`.

**Comment by romkatv** [comment]
> > If you are using Oh My Zsh, `ZSH_THEME` is where it should be.
> 
> @romkatv I tested with a fresh install of both oh-my-zsh and powerlevel10k on two machines, and on both, I had to put the `ZSH_THEME` before `source ...`.

Of course. It looks like we are in agreement.

**Comment by junaid-ali** [comment]
Shouldn't we have it documented in the README in case someone wonders why the theme isn't applied?

**Comment by romkatv** [comment]
Didn't you just confirm that `ZSH_THEME` is already where it should be in zshrc with oh my zsh?

**Comment by romkatv** [comment]
If you move things around, you can break your config. If you think your zsh framework of choice doesn't make it clear, consider filing a bug against it.

**Comment by junaid-ali** [comment]
I think we are understanding it a bit differently here, or I'm not able to explain it properly. I'm fine with closing this PR, if someone stumbles upon it again, he/she can refer to what needs to be done.

**Comment by romkatv** [comment]
Oh, it is possible that we see this differently. Good point.

> the ZSH_THEME variable should be added before `source $ZSH/oh-my-zsh.sh`

It shouldn't be added anywhere. The parameter should be left where it is and its value should be set to `powerlevel10k/powerlevel10k`.

**Comment by romkatv** [comment]
Here: https://github.com/ohmyzsh/ohmyzsh/blob/50a526f209a182add8a47e362e1c9a3bfd7c5af4/templates/zshrc.zsh-template#L7

**Comment by junaid-ali** [comment]
> Here: https://github.com/ohmyzsh/ohmyzsh/blob/50a526f209a182add8a47e362e1c9a3bfd7c5af4/templates/zshrc.zsh-template#L7

ohkay, I was adding ZSH_THEME variable at the end of `.zshrc` instead of updating the existing one.

**Comment by junaid-ali** [comment]
Sorry, I misread the Step#2, and didn't realize there was an existing `ZSH_THEME` var in `.zshrc`. So, was adding a duplicate `ZSH_THEME` variable (and then moving it to before `source ... oh-my-zsh.sh`  to make it work). You're right, the variable is where it should be.

**Pull request closed without merging**
