### PR TITLE
add os_icon for Artix and Void

### PR DESCRIPTION
**Pull request by aldum**
For nerd fonts

### CODE REVIEW

**Comment by romkatv** [comment]
It's as straightforward to merge because older versions of Nerd Fonts don't have this icon. I would need to add more questions to the wizard and more font modes to differentiate between different Nerd Font versions. I cannot justify this just for this icon.

**Comment by aldum** [comment]
As you see fit.
I should note, both Artix and Void use recent versions of Nerd Fonts, this is unlikely to cause an issue in practice.

**Comment by romkatv** [comment]
> I should note, both Artix and Void use recent versions of Nerd Fonts, this is unlikely to cause an issue in practice.

Even though most users enable `os_icon` purely for decoration, it does have a function. When you SSH to a remote machine, it's nice to know whether it's Debian, CentOS or FreeBSD, because this affects how you do common tasks. In this case the font comes from your local machine.

**Comment by Pukimaa** [comment]
Just merge this one and add EndeavourOS Icon too. I don't know why my issue got closed. Just because we can do it ourselves doesn't mean it shouldn't be implemented. I can add every icon I want but it's just locally in my config and requires users as me to search how to switch it. This heavily decreases the UX.

**Comment by romkatv** [comment]
> Just merge this one and add EndeavourOS Icon too. I don't know why my issue got closed.

Please see the first comment on this PR.

**Pull request closed without merging**
