### PR TITLE
Fix broken links in README.md

### PR DESCRIPTION
**Pull request by beni0888**
This commit fixes several broken links in the README.md file.

### CODE REVIEW

**Comment by romkatv** [comment]
What do you mean by broken links? Can you describe how to reproduce their brokenness?

**Comment by beni0888** [comment]
@romkatv I'm sorry for my late reply, I've just read your comment... What I meant is that in the README.md file there are some internal links to some sections of the document that are broken (those which I fix). In order to reproduce the issue, you just need to open the README.md file through the GitHub web UI in a browser (I tested it in Chrome in OSX) and click on the mentioned links, you will see that they don't take you anywhere. 
I hope you can still re-open the PR and apply the fix.

**Comment by romkatv** [comment]
Here's how I've tried to reproduce this in Chrome on Windows 10:

1. Open https://github.com/romkatv/powerlevel10k/blob/master/README.md.
2. Search for "What is the best prompt style in the configuration wizard".
3. Click on the first link that matches.

This leads to https://github.com/romkatv/powerlevel10k/blob/master/README.md#what-is-the-best-prompt-style-in-the-configuration-wizard as expected.

I'll try to reproduce this on macOS later.

**Comment by beni0888** [comment]
You're right, I've just checked in Chrome OSX  and it turns out that it works now... I don't know why it failed for me back then... Anyway, forget about this and excuse me for the noise 🙂

**Pull request closed without merging**
