### PR TITLE
Makefile: optimize recursive invocation

### PR DESCRIPTION
**Pull request by ratijas**
I made it with GitHub web editor. Please, test carefully before merging!

### CODE REVIEW

**Comment by romkatv** [comment]
This generates warnings.

What advantages does it have?

**Comment by ratijas** [comment]
Can you post the warnings, please?

To the best of my knowledge, `-C` is a popular choice for recursive Makefile scripts, especially those generated by cmake.

**Comment by romkatv** [comment]
> Can you post the warnings, please?

Not at the moment, no.

What advantages does this PR have?

**Comment by ratijas** [comment]
Lemme build it myself, so I'll see...

> What advantages does this PR have?

None, except for the obvious ones: you don't have to tamper with `$PWD` and ensure it is properly restored — child process isolates that.

**Comment by romkatv** [comment]
OK, I've found the warning in my history. It's only generated when you invoke `make` but not `$(MAKE)`, so this PR is fine. Merging.

> > What advantages does this PR have?
> 
> None

Thanks. In the future, when sending a PR, please specify clearly what advantages will it confer.

> you don't have to tamper with `$PWD` and ensure it is properly restored — child process isolates that.

It's in a subshell anyway. I don't really need to `cd` back, it's automatic.

> If you don't like the wording of title

I don't mind the title as long as I understand the purpose of a PR. The purpose of this one wasn't clear, so I've asked.

**Comment by ratijas** [comment]
Oh, sorry about that. I should've put a little bit more effort into creating PR.

> It's in a subshell anyway. I don't really need to cd back, it's automatic.

Well, you don't have to think about or assume it. How about that? xD

**Comment by romkatv** [comment]
> Well, you don't have to think about or assume it. How about that? xD

I agree this is simpler, this is why I merged it.

**Pull request merged**
