### PR TITLE
Add ZPM plugin manager

### PR DESCRIPTION
**Pull request by zfben**

### CODE REVIEW

**Comment by romkatv** [comment]
Can you put a full sentence in there?

**Comment by zfben** [comment]
> Can you put a full sentence in there?

Is it better now?

**Comment by romkatv** [comment]
Will the effects of this command persist after rebooting the machine or does it affect only the current shell session?

**Comment by zfben** [comment]
There is something wrong, I will reopen this request when zpm can work with powerlevel10k.

**Pull request closed without merging**
