### PR TITLE
Add remotes of some git server instances

### PR DESCRIPTION
**Pull request by hasecilu**
Currently only icons for big providers of git hosting service are available.

Organizations of open source software usually manage their own instances.

Adding the remote addresses of some of this organizations will let us to identify via a glyph icon the remote providing the source code.

For example some `gitlab` instances in the wild like the ones from GNOME, freedesktop.org, KDE organization can get a more personal touch.

-  **Arch Linux** (https://gitlab.archlinux.org): Hosting their tools, mirrors, etc. Merge requests and Issues will be open to users in the foreseeable future.
-  **freedesktop.org** (https://gitlab.freedesktop.org): Software focused on interoperability and shared technology for open-source graphical and desktop systems.
-  **GNOME** (https://gitlab.gnome.org): Software from GNOME project.
-  **Codeberg** (https://codeberg.org): Collaboration platform providing Git hosting and services for free and open source software, content and projects. .
-  **Debian** (https://salsa.debian.org) Repository of Debian.
-  **FreeBSD** (https://cgit.freebsd.org): FreeBSD project.
-  **GNU** (https://www.gnu.org): GNU packages.
-  **KDE** (https://invent.kde.org): Software from GNOME project.
-  **Linux** (https://kernel.org/): The Linux kernel projects.

The Debian and KDE instances didn't use `gitlab` subdomain making it to not even being recognized as `gitlab` instance getting the `git` icon.

**NOTE:** Some glyphs are from Nerd Fonts 3.1.0, you may need to update your font.

**ANOTHER NOTE:** In the FreeBSD section `(#i)` is used because FreeBSD uses uppercases on their git commands and if someone don't change it to lowercase it wouldn't get the FreeBSD icon.

**IMPORTANT NOTE:** The logo used for KDE organization is the logo from their KDE Plasma desktop environment because in NerdFont the KDE logo is not available, I can merge it to `font-logos` project to then submit it to NF but will not be available until NF next release.

screenshot1700779456

### CODE REVIEW

**Comment by romkatv** [comment]
Very nice! Thanks for the PR.

Some of the icons are unavailable in Nerd Fonts v3.0 and the wizard currently does not attempt to detect fonts with a higher version than that. Eventually I'll add such detection but it's too early to do so. Are there reasonable alternatives for the following icons for people using Nerd Fonts v3.0?

- VCS_GIT_CODEBERG_ICON
- VCS_GIT_FREEDESKTOP_ICON
- VCS_GIT_GNOME_ICON
- VCS_GIT_KDE_ICON

If these are all hosted by gitlab, perhaps a gitlab logo?

**Comment by hasecilu** [comment]
Codeberg is not a gitlab instance, it uses forgejo. The gitea and forgejo logos were also added on Nerd Font 3.1.0 in case someone need to use them.

The GNOME and freedesktop.org instances already have the gitlab logo because "gitlab" is their subdomain, in case of KDE they use "invent" and get the git logo.

**Comment by romkatv** [comment]
Are there reasonable alternatives for the following icons for people using Nerd Fonts v3.0?

- VCS_GIT_CODEBERG_ICON
- VCS_GIT_FREEDESKTOP_ICON
- VCS_GIT_GNOME_ICON
- VCS_GIT_KDE_ICON

I cannot merge the PR as is because it'll result in broken icons for people on Nerd Fonts v3.0.

**Comment by hasecilu** [comment]
What do you think about to directly assigning `VCS_GIT_ICON` to codeberg and `VCS_GIT_GITLAB_ICON` to the other 3 without modifying the `icons.zsh` file and when 3.1.0 is properly supported revert that change.

**Comment by romkatv** [comment]
Thanks, that's exactly what I was asking: which fallback to use. You gave me the right kind of info. You don't need to make any changes to the PR, I'll do it myself.

**Comment by ShellTux** [comment]
Hey, I really like using p10k to theme my zsh prompt, I would like to contribute to this project
So I have some repos where the remote repo is a gitea server.
I would like to have a gitea icon for those repos, and I found that recent version of nerd fonts have a gitea icon.
So I found this pull request, instead of creating a new pull request, can I submit a new commit for this one?
by just implementing `VCS_GIT_GITEA_ICON` to '\uF339 ' and add the rest accordingly

**Comment by hasecilu** [comment]
I think that would be cool but since the gitea icon is from NF 3.1.0 I don't know if romkatv would like to a change of something before.

**Comment by hasecilu** [comment]
I just remembered about another repository called sourcehut (https://sourcehut.org), where the repos are hosted at `https://sr.ht` their logo is a circle, so we can use `nf-fa-circle_thin` at \uf1db ().

**Comment by romkatv** [comment]
I've merged this PR and applied a few changes on top. If your font has Nerd Fonts v3.1 icons, you can use them like this:

```zsh
typeset -g POWERLEVEL9K_VCS_GIT_CODEBERG_ICON='\uF330'
```

You can now also override the mapping from remote git URLs to icons. See https://github.com/romkatv/powerlevel10k/commit/7fd76370f53f87f956c811766a452c83ced4014b.

**Comment by hasecilu** [comment]
> **IMPORTANT NOTE:** The logo used for KDE organization is the logo from their KDE Plasma desktop environment because in NerdFont the KDE logo is not available, I can merge it to `font-logos` project to then submit it to NF but will not be available until NF next release.


Hi, release of Nerd Fonts 3.2.0 has been done, so, the KDE logo is now available as `nf-linux-kde` at `\uf373` 

**Pull request merged**
