### PR TITLE
Add CPU load threshold setting

### PR DESCRIPTION
**Pull request by Mellbourn**
This PR adds a threshold setting to the CPU load segment below which it is completely hidden

Motivation: I think many users prefer prompts that are simple under "normal" circumstances. If the CPU load is at a level that is not worrisome, it is better to hide it.

The suggested default threshold is 40%, this can of course be changed to something else before accepting the PR.

This is my first PR to this repo, so it wouldn't surprise me if I missed something, please comment if that is so.

### CODE REVIEW

**Comment by romkatv** [comment]
CPU usage is not a property of a shell session, so users who optimize prompt for productivity don't enable it. It's essentially a decorative segment. Users who enable it just want to see the icon.

I'm fine with adding the new parameter but please make the default 0 (so that the segment is always shown) and revert the changes in the `config` directory.

**Comment by Mellbourn** [comment]
Done!

**Comment by romkatv** [comment]
Thanks!

**Comment by Mellbourn** [comment]
I think my implementation is buggy: 
The segment is hidden if it is lower than the threshold when the prompt is first shown in a session.
But if the segment is first shown (due to being above the threshold), and then falls below the threshold, it is not hidden, it keeps showing the old value.
I've attempted to fix it, but I'm not sure how to clear the segment properly.

I tried to add an `echo` below line 2280 but it didn't make any difference
```javascript
  if (( pct < _POWERLEVEL9K_LOAD_THRESHOLD )); then
    echo -E - 'reset=1'
    return
```

**Comment by romkatv** [comment]
I've removed `POWERLEVEL9K_LOAD_THRESHOLD` and added ` POWERLEVEL9K_LOAD_{WARNING,CRITICAL}_PCT` instead. You can set  `POWERLEVEL9K_LOAD_WARNING_PCT` to the threshold value and hide `load` in `NORMAL` state.

```zsh
# Hide `load` when it's under 10% of all CPUs.
POWERLEVEL9K_LOAD_WARNING_PCT=10
POWERLEVEL9K_LOAD_NORMAL_CONTENT_EXPANSION=
POWERLEVEL9K_LOAD_NORMAL_VISUAL_IDENTIFIER_EXPANSION=
```

**Pull request merged**
