### PR TITLE
add fluxctl and stern to show kubecontext

### PR DESCRIPTION
**Pull request by bcochofel**
Add fluxctl and stern to kubecontext

### CODE REVIEW

**Comment by romkatv** [comment]
Do both of these tools respect the current context set in `~/.kube/config`?

**Comment by bcochofel** [comment]
> Do both of these tools respect the current context set in `~/.kube/config`?

yes :-)

**Comment by romkatv** [comment]
> > Do both of these tools respect the current context set in `~/.kube/config`?
> 
> yes :-)

Can you help me to get convinced? Links to documentation and/or code would help.

I'm asking this because in the past several PRs that did something similar were erroneous. Since I don't use the tools in question, I don't know if this PR is correct or not.

**Comment by bcochofel** [comment]
> > > Do both of these tools respect the current context set in `~/.kube/config`?
> > 
> > 
> > yes :-)
> 
> Can you help me to get convinced? Links to documentation and/or code would help.
> 
> I'm asking this because in the past several PRs that did something similar were erroneous. Since I don't use the tools in question, I don't know if this PR is correct or not.

Hope this helps to clarify this.

regarding fluxctl: https://docs.fluxcd.io/en/latest/references/fluxctl/ (--context parameter)
regarding stern: https://github.com/wercker/stern (--context parameter)

https://kubernetes.io/blog/2016/10/tail-kubernetes-with-stern/

**Comment by romkatv** [comment]
> Hope this helps to clarify this.
> 
> regarding fluxctl: https://docs.fluxcd.io/en/latest/references/fluxctl/ (--context parameter)

I took a look at this one but wasn't able to find where it says that `fluxctl` respects the current context set in `~/.kube/config`. Could you point me to a more specific place that describes this?

**Comment by bcochofel** [comment]
> > Hope this helps to clarify this.
> > regarding fluxctl: https://docs.fluxcd.io/en/latest/references/fluxctl/ (--context parameter)
> 
> I took a look at this one but wasn't able to find where it says that `fluxctl` respects the current context set in `~/.kube/config`. Could you point me to a more specific place that describes this?

The --context parameter lets you change the context, but if you don't use it it gets the current one.

**Comment by romkatv** [comment]
Where does it get the current context from?

**Comment by bcochofel** [comment]
> Where does it get the current context from?

by default, on linux, ~/.kube/config

**Comment by romkatv** [comment]
> > Where does it get the current context from?
> 
> by default, on linux, ~/.kube/config

That's good. Can you point me to documentation or code that confirms this?

**Comment by bcochofel** [comment]
> > > Where does it get the current context from?
> > 
> > 
> > by default, on linux, ~/.kube/config
> 
> That's good. Can you point me to documentation or code that confirms this?

Hope this helps to clarify this: https://github.com/fluxcd/flux/blob/4b34312ba55a2e9facd2315ab30a1f530eb144cc/cmd/fluxctl/args.go#L55

**Comment by romkatv** [comment]
> > That's good. Can you point me to documentation or code that confirms this?
> 
> Hope this helps to clarify this: https://github.com/fluxcd/flux/blob/4b34312ba55a2e9facd2315ab30a1f530eb144cc/cmd/fluxctl/args.go#L55

I'm afraid it doesn't.

Since it's unclear to me whether `fluxctl` and `stern` respect the current context set in `~/.kube/config`, I'll need to spend time to find out. I might get around to doing this in a few months but there is no guarantee.

I suppose this isn't inconveniencing you because you can apply these same changes to your own config.

**Comment by bcochofel** [comment]
> > > That's good. Can you point me to documentation or code that confirms this?
> > 
> > 
> > Hope this helps to clarify this: https://github.com/fluxcd/flux/blob/4b34312ba55a2e9facd2315ab30a1f530eb144cc/cmd/fluxctl/args.go#L55
> 
> I'm afraid it doesn't.
> 
> Since it's unclear to me whether `fluxctl` and `stern` respect the current context set in `~/.kube/config`, I'll need to spend time to find out. I might get around to doing this in a few months but there is no guarantee.
> 
> I suppose this isn't inconveniencing you because you can apply these same changes to your own config.

Yes, I'm currently using that changed config

**Comment by bcochofel** [comment]
```
❯ fluxctl --help
fluxctl helps you deploy your code.

Connecting:

  # To a fluxd running in namespace "default" in your current kubectl context
  fluxctl list-workloads

  # To a fluxd running in namespace "weave" in your current kubectl context
  fluxctl --k8s-fwd-ns=weave list-workloads

  # To a Weave Cloud instance, with your instance token in $TOKEN
  fluxctl --token $TOKEN list-workloads

Workflow:
  fluxctl list-workloads                                                   # Which workloads are running?
  fluxctl list-images --workload=default:deployment/foo                    # Which images are running/available?
  fluxctl release --workload=default:deployment/foo --update-image=bar:v2  # Release new version.

Usage:
  fluxctl [command]

Available Commands:
  automate       Turn on automatic deployment for a workload.
  completion     Output shell completion code for the specified shell (bash, zsh, or fish)
  deautomate     Turn off automatic deployment for a workload.
  help           Help about any command
  identity       Display SSH public key
  install        Print and tweak Kubernetes manifests needed to install Flux in a Cluster
  list-images    Show deployed and available images.
  list-workloads List workloads currently running in the cluster.
  lock           Lock a workload, so it cannot be deployed.
  policy         Manage policies for a workload.
  release        Release a new version of a workload.
  save           save workload definitions to local files in cluster-native format
  sync           synchronize the cluster with the git repository, now
  unlock         Unlock a workload, so it can be deployed.
  version        Output the version of fluxctl

Flags:
      --context string                  The kubeconfig context to use, will use your current selected if not specified
  -h, --help                            help for fluxctl
      --k8s-fwd-labels stringToString   Labels used to select the fluxd pod a port forward should be created for. You can also set the environment variable FLUX_FORWARD_LABELS (default [app=flux])
      --k8s-fwd-ns string               Namespace in which fluxd is running, for creating a port forward to access the API. No port forward will be created if a URL or token is given. You can also set the environment variable FLUX_FORWARD_NAMESPACE (default "default")
      --timeout duration                Global command timeout; you can also set the environment variable FLUX_TIMEOUT (default 1m0s)
  -t, --token string                    Weave Cloud authentication token; you can also set the environment variable WEAVE_CLOUD_TOKEN or FLUX_SERVICE_TOKEN
  -u, --url string                      Base URL of the Flux API (defaults to "https://cloud.weave.works/api/flux" if a token is provided); you can also set the environment variable FLUX_URL

Use "fluxctl [command] --help" for more information about a command.
```

the `--context` can clarify this

**Comment by bcochofel** [comment]
And for `stern`:

```
❯ stern --help
Tail multiple pods and containers from Kubernetes

Usage:
  stern pod-query [flags]

Flags:
      --all-namespaces             If present, tail across all namespaces. A specific namespace is ignored even if specified with --namespace.
      --color string               Color output. Can be 'always', 'never', or 'auto' (default "auto")
      --completion string          Outputs stern command-line completion code for the specified shell. Can be 'bash' or 'zsh'
  -c, --container string           Container name when multiple containers in pod (default ".*")
      --container-state string     If present, tail containers with status in running, waiting or terminated. Default to running. (default "running")
      --context string             Kubernetes context to use. Default to current context configured in kubeconfig.
  -e, --exclude strings            Regex of log lines to exclude
  -E, --exclude-container string   Exclude a Container name
  -h, --help                       help for stern
  -i, --include strings            Regex of log lines to include
      --kubeconfig string          Path to kubeconfig file to use
  -n, --namespace string           Kubernetes namespace to use. Default to namespace configured in Kubernetes context
  -o, --output string              Specify predefined template. Currently support: [default, raw, json] (default "default")
  -l, --selector string            Selector (label query) to filter on. If present, default to ".*" for the pod-query.
  -s, --since duration             Return logs newer than a relative duration like 5s, 2m, or 3h. Defaults to 48h.
      --tail int                   The number of lines from the end of the logs to show. Defaults to -1, showing all logs. (default -1)
      --template string            Template to use for log lines, leave empty to use --output flag
  -t, --timestamps                 Print timestamps
  -v, --version                    Print the version and exit
```

**Comment by romkatv** [comment]
What should I understand from your last two comments?

**Comment by bcochofel** [comment]
> What should I understand from your last two comments?

Both describe that the `--context` default to the current kubeconfig

**Comment by romkatv** [comment]
> > What should I understand from your last two comments?
> 
> Both describe that the `--context` default to the current kubeconfig

That's nice. Does it also say somewhere how default is computed?

By the way, in case this isn't clear, all my questions are just the repeating of a single question. Before adding a command to `POWERLEVEL9K_KUBECONTEXT_SHOW_ON_COMMAND` I need to know that this command respects the current context set in `~/.kube/config`. That's all there is. I could spend my own time to figure this out or you could do it and tell me where to look.

If I may ask, could you resist from posting additional comments *unless* those comments unambiguously point to documentation and/or code that supports the statement that these two commands respects the current context set in `~/.kube/config`? I realise it may not be easy for you to do this but I also have to put some limit on my own time.

**Comment by bcochofel** [comment]
I understand your point. Let me just say that there are more ways to configure access to kubernetes cluster, not just the default `~/.kube/config` 

https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/

"Note: A file that is used to configure access to a cluster is sometimes called a kubeconfig file. This is a generic way of referring to configuration files. It does not mean that there is a file named kubeconfig."

"The KUBECONFIG environment variable is a list of paths to configuration files. The list is colon-delimited for Linux and Mac, and semicolon-delimited for Windows."

So the tools use this kubeconfig reference since this is the generic way of referring to configuration files.

I can tell you that I use `kubectx` to change context and use both stern and fluxctl after that.

**Comment by romkatv** [comment]
> I understand your point. Let me just say that there are more ways to configure access to kubernetes cluster, not just the default `~/.kube/config`
> 
> https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/
> 
> "Note: A file that is used to configure access to a cluster is sometimes called a kubeconfig file. This is a generic way of referring to configuration files. It does not mean that there is a file named kubeconfig."
> 
> "The KUBECONFIG environment variable is a list of paths to configuration files. The list is colon-delimited for Linux and Mac, and semicolon-delimited for Windows."

Yep, I know that much. Powerlevel10k implements this logic.

> So the tools use this kubeconfig reference since this is the generic way of referring to configuration files.
> 
> I can tell you that I use `kubectx` to change context and use both stern and fluxctl after that.

That's convincing enough. Thanks! Merging.

Thanks for the PR!

**Pull request merged**
