### PR TITLE
Add support for termux-battery-status

### PR DESCRIPTION
**Pull request by Freed-Wu**
It's a contiuance of <https://github.com/romkatv/powerlevel10k/issues/803#issuecomment-703190306>

Thanks for your review!

### CODE REVIEW

**Comment by Freed-Wu** [comment]
Screenshot_2021-03-07-03-27-18-57

it can work, but it need more test and improvement.

**Comment by Freed-Wu** [comment]
maybe this line is problematic:

```sh
    (( bat_percent = `termux-battery-status|jq -r .percentage` ))
```
Screenshot-20210307033452-1366x768

this is `/data/.profile`, when `su - u0_a205`, this file will be sourced.

```sh
	export PREFIX=/data/data/com.termux/files/usr
	export PATH=$PREFIX/bin:$PATH
	export HOME=/data/data/com.termux/files/home
	cd
	exec $PREFIX/bin/zsh
```

**Comment by Freed-Wu** [comment]
> maybe this line is problematic:
> 
> ```shell
>     (( bat_percent = `termux-battery-status|jq -r .percentage` ))
> ```

it is because termux-battery-status cannot work normally in adb shell.
perhaps should get battery information from acpiclient more priorer than termux-battery-status to solve the problem.

**Comment by Freed-Wu** [comment]
termux api only can work for termux user, not root or shell (adb shell user). so should get battery information from acpiclient prior to termux api.

Now it can work for whoever termux user or root user. the bug that percentage of battery capcity is 0% will be fixed in <https://github.com/romkatv/powerlevel10k/pull/1288>.

Screenshot_2021-03-07-15-59-22-43

**Comment by romkatv** [comment]
`termux-battery-status` hangs by default unless Termux:API is installed and given extra permissions. Thus, it's unsafe to invoke it without first ensuring that it won't hang. This is a deal breaker.

In addition, please remove all forks from the code you are adding. The only new fork can be the invocation of `termux-battery-status`.

**Comment by Freed-Wu** [comment]
i am sorry:(

i asked this question to termux, they added an 'enhance' label for it.
since now, i still don't know how to judge if Termux:API will hang and how to avoid this insafe invoke.

sorry again.

**Comment by Freed-Wu** [comment]
> termux-battery-status hangs by default unless Termux:API is installed

Can we add a variable, when user make sure they have installed Termux:API, they set it, p10k will use it to display battery info? Because this variable if unset by default, it will effect other users.

**Comment by romkatv** [comment]
Can you elaborate why you want this segment visible? Doesn't your device already show battery level at the top?

**Comment by romkatv** [comment]
Thank you for explaining the motivation for displaying batter charge level in the shell prompt when the same information is available at the top of the screen.

The reason you've provided appears to me as a desirable feature rather than an issue issue to be solved or worked around: battery level changes slowly, so there is no need for the battery indicator to insert itself into the active working area of an app.

However, if you feel like you need this, you can send me a clean PR (no unnecessary forks, correct and complete code that follows the local style, etc.), I'll merge it. I don't recommend it but it's an option.

**Pull request closed without merging**
