### PR TITLE
chezmoi: add chezmoi prompt

### PR DESCRIPTION
**Pull request by Alkindi42**
Hi,
I would like to add [chezmoi](https://github.com/twpayne/chezmoi) prompt. Do you think this something that could be integrated into p10k?

To give you some context, when I run `chezmoi cd`, chezmoi creates a shell and sets various environment variables. So the plan is to show the prompt  when we detect the `CHEZMOI` variable.

Before to finish my PR I would like to know what do you think about this idea.

Even if you reject this PR, I have technical question for you. I can't apply color to my prompt. I'm using `pure` theme, I tried to create `typeset -g POWERLEVEL9K_CHEZMOI_FOREGROUND=$grey` in `config/p10k-pure.zsh` without success.

Screenshot 2023-05-18 at 12 09 39

### CODE REVIEW

**Comment by romkatv** [comment]
You can implement it as a custom prompt segment. First, add this to `~/.zshrc`:

```zsh
prompt_my_chezmoi p10k segment -f 1 -t "${CHEZMOI//\%/%%}"
```

Then add `my_chezmoi` to `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS`.

Prefix "my_" will ensure that your config won't break should I add "chezmoi" prompt segment to powerlevel10k in the future.

See docs by running `p10k help segment`. Also note that you'll probably be better off with *Lean* style instead of *Pure*. The latter is a faithful emulation of another theme (https://github.com/sindresorhus/pure). It's worse in all respects than Lean. It exists to ease the migration for the users of the original pure theme.

**Comment by Alkindi42** [comment]
Thanks for your quick answer.
Yes, I know I can implement it as a custom prompt segment, but do you think it might be worth implementing it upstream? (internal)

> Also note that you'll probably be better off with Lean style instead of Pure. The latter is a faithful emulation of another theme (https://github.com/sindresorhus/pure). It's worse in all respects than Lean. It exists to ease the migration for the users of the original pure theme.

Good to know, I have updated.

**Comment by Alkindi42** [comment]
Yes but It was the same for all segments, right? (python venv, ...).

**Comment by romkatv** [comment]
Thanks! This needs a handful of small changes but it's a good-enough base. I'll merge it later this week.

**Comment by romkatv** [comment]
I see that you've marked the PR as *work in progress*, so I'm not merging it yet.

**Comment by Alkindi42** [comment]
> Ideally, `chezmoi` segment should be implemented as similarly as possible to `xplr`. See [9c03410](https://github.com/romkatv/powerlevel10k/commit/9c034101fe3cec1e2edb8e07c32a3e6dba9afaee).

Ok I will check when I have a little more time.

**Comment by felipecrs** [comment]
Out of curiosity:

- #1708

**Comment by Alkindi42** [comment]
> Out of curiosity:
> 
>     * [Support for `chezmoi status` in prompt #1708](https://github.com/romkatv/powerlevel10k/issues/1708)

Interesting. Did you give up?

@romkatv Is it really necessary to implement the **instant_prompt** function? I don't really understand how it works.
I updated my PR and removed the draft status. Don't hesitate if you want I add/change anything.

**Comment by romkatv** [comment]
> @romkatv Is it really necessary to implement the **instant_prompt** function? I don't really understand how it works.

Yes, it is necessary. Thankfully, it's not necessary to understand how it works. If you copy and modify https://github.com/romkatv/powerlevel10k/commit/9c034101fe3cec1e2edb8e07c32a3e6dba9afaee, it'll work the way it should. Do you want to give it a shot?

**Comment by Alkindi42** [comment]
Is it ok for you?

**Comment by romkatv** [comment]
I'll take a look later today or tomorrow.

**Comment by romkatv** [comment]
Merged with a bunch of changes.

**Comment by Alkindi42** [comment]
Thanks @romkatv.

I saw your updated and I have a question.

How do you choose the right value for the `POWERLEVEL9K_CHEZMOI_SHELL_FOREGROUND` variable?

**Comment by romkatv** [comment]
First I went to chezmoi.io to check which color they use. It's blue. Then I looked at the 256 colors for a shade that is relatively bright and isn't too far from the upstream choice. This is the color for the 256-color configs. For 8-color configs the choice is simple because only one of these 8 colors is blue.

**Pull request merged**
