### PR TITLE
Typo in README.md

### PR DESCRIPTION
**Pull request by crydotsnake**

### CODE REVIEW

**Comment by romkatv** [comment]
Could you clarify the motivation behind this change? Does the original code not work for you?

**Comment by crydotsnake** [comment]
@romkatv Sure!. 

There was a typo, 

Before: Set `ZSH_THEME=powerlevel10k/powerlevel10k` in your `~/.zshrc`.

After: Set `ZSH_THEME="powerlevel10k/powerlevel10k"` in your `~/.zshrc`.

**Comment by romkatv** [comment]
"Typo" implies that the new version of the code was intended all along. It wasn't.

Why do you think this PR is an improvement? Is it fixing anything for you?

**Comment by crydotsnake** [comment]
Oh, i didnt know that `ZSH_THEME="powerlevel10k/powerlevel10k"` also works without the `""`... Sorry!!.

**Comment by romkatv** [comment]
> Oh, i didnt know that `ZSH_THEME="powerlevel10k/powerlevel10k"` also works without the `""`... Sorry!!.

Oh, I see. I got really confused when I saw this PR :grin:

Yes, there is no difference. You can also do these:

```zsh
ZSH_THEME='powerlevel10k/powerlevel10k'
ZSH_THEME="powerlevel10k"/powerlevel10k
typeset ZSH_THEME=powerlevel10k/powerlevel10k
typeset -g ZSH_THEME=powerlevel10k/powerlevel10k
```

**Comment by crydotsnake** [comment]
Okay, thanks!. And Sorry again for confusing!. Then i will find a another way, to contribute to this amazing project! :P.

**Pull request closed without merging**
