### PR TITLE
Remove geopolitical term

### PR DESCRIPTION
**Pull request by mmathys**

### CODE REVIEW

**Comment by romkatv** [comment]
I added the gitee mirror after I was informed that github is extremely slow to access from mainland China. Are you saying that this is also the case for Hong Kong, Taiwan and other places that are part of China but not of mainland China?

**Comment by mmathys** [comment]
Sorry for the vague description of this pull request. The term "mainland China" is often [used to imply](https://www.us-taiwan.org/resources/what-does-using-the-term-mainland-china-imply-for-taiwan/#:~:text=The%20term%20%E2%80%9CMainland%20China%E2%80%9D%20tacitly,%2C%20and%20cross%2DStrait%20relations.) that Taiwan is part of China.

**Comment by romkatv** [comment]
What would be a more accurate way to describe the territory on which the access to github is extremely slow due to the interference by the China's firewall? Is that "China"?

**Comment by mmathys** [comment]
Yes, "China" (or "PRC")

**Comment by romkatv** [comment]
Thanks! Merged.

**Comment by CoelacanthusHex** [comment]
China is wrong, but PRC is correct. Taiwan or ROC is a part of China. China Mainland or PRC is also a part of China.
If someone said Republic Of China is not a part of China, Chiang Kai-shek and Sun Yat-sen will be upset. (Both of them are former ROC leaders.)

**Comment by CoelacanthusHex** [comment]
For historical reasons, there are two parallel regimes in China, the Republic of China and the People's Republic of China, with the former in de facto control of the Taiwan area and the latter in de facto control of the mainland area, both of which consider themselves to be the sole legitimate government of China.

**Comment by CoelacanthusHex** [comment]
That's why I chose geographic terms to avoid political issues on both sides (neither side recognizes the legitimacy of the other's government).

**Pull request merged**
