### PR TITLE
support battery for Android

### PR DESCRIPTION
**Pull request by Freed-Wu**
Screenshot_20240412_021027_com android systemui

### CODE REVIEW

**Comment by romkatv** [comment]
This will increase the startup time by 1s for some users. It will also not work reliably when the machine is slow during zsh startup: 1s may not be enough.

We need a fast and reliable way of figuring out whether `termux-battery-status` works.

**Comment by Freed-Wu** [comment]
```zsh
$+commands[termux-battery-status] == 1 && -n $(timeout 1 termux-battery-status)
```

> This will increase the startup time by 1s for some users

If user don't install `termux-battery-status`, the code after `&&` will not be executed. So it should only effect very few people?

> 1s may not be enough

If `1s` is not enough, I recommend to disable this feature for those slow machine. I think this code should do this work (disable), really?

**Comment by romkatv** [comment]
I understand your point but mine still stands.

**Comment by Freed-Wu** [comment]
> I understand your point but mine still stands.

So can we add a variable which is 0 and if user set it to 1 which means user ensure they can take duty for themselves, then this code will be enabled?

**Comment by romkatv** [comment]
Yes, that would be fine.

**Comment by romkatv** [comment]
Please post an example output of `termux-battery-status`. And if you know where the documentation for this output can be found, please link/post that too.

**Comment by Freed-Wu** [comment]
Any other problem?

**Comment by romkatv** [comment]
I started reviewing (and rewriting) this code and then gave up after being unable to find the list of supported `status` values. It's difficult for me to find motivation to work on this PR given how marginal the improvement (most Android users already can see battery on their screen) and how much trouble it is.

**Comment by Freed-Wu** [comment]
There are two situations users cannot see battery on status bar:

1. Android apk has fullscreen mode
2. ssh an Android

IMG20240424153432

**Comment by romkatv** [comment]
Of course. Hence "most".

Do you know where I can find the list of possible `status` values?

**Comment by Freed-Wu** [comment]
https://github.com/termux/termux-api/blob/4c6a5196c969a54c32bbe3fc034e0cdc64e83f04/app/src/main/java/com/termux/api/apis/BatteryStatusAPI.java#L85-L101

**Comment by romkatv** [comment]
Thanks. I'll have another shot at this PR.

**Comment by romkatv** [comment]
I don't think I'll ever find time to work on this. Sorry. Consider using your own fork if the code does what you need.

**Pull request closed without merging**
