### PR TITLE
support wifi for Android

### PR DESCRIPTION
**Pull request by Freed-Wu**
Screenshot_20240412_023146_com termux

### CODE REVIEW

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k/pull/2639#issuecomment-2053567853 applies here, too.

**Comment by romkatv** [comment]
Please post an example output of `termux-wifi-connectioninfo`. And if you know where the documentation for this output can be found, please link/post that too.

**Comment by romkatv** [comment]
This API does not seem to provide noise. I'm not sure how to adjust the math without it.

**Comment by romkatv** [comment]
> > provide noise
> 
> What is noise? Can we skip it?

I'm referring to the "noise" variable in the function you are modifying.

**Comment by Freed-Wu** [comment]
> "noise" variable in the function you are modifying.

How can we handle it? Keep it as a default value?

**Comment by romkatv** [comment]
The existing code does not work without "noise". If there is no "noise" on some devices, then this segment cannot work on them seamlessly. I don't know how the code can be adapted though.

**Comment by Freed-Wu** [comment]
> does not work

It can display wifi information in my Android. What does `does not work` means? Any potential bug?

**Comment by romkatv** [comment]
The existing code requires `noise`. Setting it to zero, as your PR does, will cause this code to work incorrectly when the actual noise is non-zero.

**Comment by romkatv** [comment]
I don't think I'll ever find time to work on this. Sorry. Consider using your own fork if the code does what you need.

**Pull request closed without merging**
