### PR TITLE
Show kubecontext when using `kubeseal` or `skaffold`

### PR DESCRIPTION
**Pull request by omus**

### CODE REVIEW

**Comment by romkatv** [comment]
Does the behavior of `kubeseal` and `skaffold` depend on the content of `~/.kube/config`?

**Comment by omus** [comment]
> Does the behavior of `kubeseal` and `skaffold` depend on the content of `~/.kube/config`?

I don't believe so. Is there something specific you have in mind?

**Comment by romkatv** [comment]
Your PR has the following effect: whenever one is typing a command that invokes `kubeseal` or `skaffold`, an excerpt of `~/.kube/config` is shown in prompt. Given your last comment, it's unclear why this could be desired. Could you explain the motivation behind your PR?

**Comment by omus** [comment]
> Your PR has the following effect: whenever one is typing a command that invokes `kubeseal` or `skaffold`, an excerpt of `~/.kube/config` is shown in prompt. Given your last comment, it's unclear why this could be desired. Could you explain the motivation behind your PR?

Ah, I definitely did not understand your original question. Both of these commands make use of the `current-context` defined within the `~/.kube/config` file. The `skaffold` command will use the k8s context when deploying manifests while `kubeseal` uses the current context as the default for `--context`.

Being aware of the context been used when these commands is used is important to avoid accidentally deploying manifests to the wrong k8s context/namespace.

**Comment by romkatv** [comment]
Thanks! Merged.

**Pull request merged**
