### PR TITLE
Improve Antigen configuration

### PR DESCRIPTION
**Pull request by DanielAtKrypton**
Recommended configuration file for Antigen is ~/.antigenrc.

### CODE REVIEW

**Comment by DanielAtKrypton** [comment]
An example configuration can be seen [here](https://github.com/DanielAtKrypton/debian-dev-boilerplate).

**Comment by romkatv** [comment]
I'll stick with the official documentation: https://github.com/zsh-users/antigen#usage.

**Comment by DanielAtKrypton** [comment]
@romkatv, to use `.antigenrc` is actually the recommended configuration. See the official [wiki](https://github.com/zsh-users/antigen/wiki/Quick-start).

**Comment by romkatv** [comment]
I'm sticking with the official docs. Nothing is more official than the project's homepage.

Once the homepage of antigen changes, I'll be happy to merge this PR.

**Comment by DanielAtKrypton** [comment]
Interesting line of thought!

**Comment by DanielAtKrypton** [comment]
I created a pull request to the project's homepage following your recommendation. Here it is: https://github.com/zsh-users/antigen/pull/706

**Pull request closed without merging**
