### PR TITLE
Added gsutil as is the main "other command" in GCP

### PR DESCRIPTION
**Pull request by thekoma**
Added gsutil as is the main "other command" in GCP
Looks sane to include it as default.

### CODE REVIEW

**Comment by romkatv** [comment]
Does the behavior of `gsutil` depend on the content of `~/.config/gcloud/configurations`?

**Comment by thekoma** [comment]
AFAIK yes, the authentication pattern should be the same used for gcloud.


Il dom 26 dic 2021, 16:30 Roman Perepelitsa ***@***.***> ha
scritto:

**Comment by romkatv** [comment]
After spending 10 minutes trying to answer this question I'm tempted to believe the answer is No. If you believe otherwise, please point me to the documentation or show a listing of commands that demonstrates that the behavior of `gsutil` does indeed depend on the content of `~/.config/gcloud/configurations` and `~/.config/gcloud/active_config`.

**Comment by thekoma** [comment]
As said it comes from the same [SDK](https://cloud.google.com/sdk) so it makes sense for it to be [initialized](https://cloud.google.com/sdk/docs/initializing) in the same manner :
```bash
$ gsutil config
CommandException: OAuth2 is the preferred authentication mechanism with the Cloud SDK.
Run "gcloud auth login" to configure authentication, unless:
- You don't want gsutil to use OAuth2 credentials from the Cloud SDK,
  but instead want to manage credentials with .boto files generated by
  running "gsutil config"; in which case run "gcloud config set
  pass_credentials_to_gsutil false".
- You want to authenticate with an HMAC access key and secret, in
  which case run "gsutil config -a".
```

And maybe it would be sage to add all those:
```bash
find /usr/lib/google-cloud-sdk/bin/  -maxdepth 1 -type f -exec basename {} \;|xargs |sed 's/ /|/g'

endpointscfg.py|java_dev_appserver.sh|git-credential-gcloud.sh|cloud-build-local|local-extract|gsutil|skaffold|kpt|kind|docker-credential-gcloud|bq|datalab|gcloud|cbt|minikube|dev_appserver.py|anthoscli
```

Although you don't necessary need to initialise the SDK or have the configuration or variable set as it can extract the configuration directly from metadata servers in GCE.

Source: I'm part of google cloud team :)

**Comment by romkatv** [comment]
Can you give me an example of the complete `gsutil` command (with all arguments) whose behavior depends on the content of `~/.config/gcloud/active_config`? I'll `strace` it to confirm that it at least reads `~/.config/gcloud/active_config`.

If there is an alternative way to show that the behavior of `gsutil` does indeed depend on the content of `~/.config/gcloud/active_config`, please share. I only need to know *this*. It doesn't matter how `gsutil` is initialized or where it stores credentials. The only thing that matters is whether its behavior depends on the content of `~/.config/gcloud/active_config`. If it does, then it makes sense to display the content of `~/.config/gcloud/active_config` in prompt when you are typing a `gsutil` command (this is what your PR does).

**Comment by thekoma** [comment]
You mean that if the configuration is not sourced from here, there is a chance that you are not able to extract the value needed to be shown.

Gotcha.
Let me do a little research.

**Comment by romkatv** [comment]
> You mean that if the configuration is not sourced from here, there is a chance that you are not able to extract the value needed to be shown.

Something like that. Or to put it another way, `gcloud` prompt segment in powerlevel10k displays the content of `~/.config/gcloud/active_config`. If the behavior of `gsutil` does not depend on the content of this file, there is no point in showing it in prompt when the user is typing a `gsutil` command, and hence no point in adding `gsutil` to `POWERLEVEL9K_GCLOUD_SHOW_ON_COMMAND`.

**Comment by thekoma** [comment]
This is tricky. gsutil invoke gcloud libraryes which invoke the file:

Without follow:
```bash
❯ truncate -s0 debug.log; strace -o debug.log gsutil version; grep active_config debug.log
gsutil version: 5.5
```

With follow:
```
❯ truncate -s0 debug.log; strace -o debug.log -f gsutil version; grep active_config debug.log
gsutil version: 5.5
550973 openat(AT_FDCWD, "/usr/local/google/home/thekoma/.config/gcloud/active_config", O_RDONLY|O_CLOEXEC) = 3
550973 openat(AT_FDCWD, "/usr/local/google/home/thekoma/.config/gcloud/active_config", O_RDONLY|O_CLOEXEC) = 3
```
So the reply is YOS or NAY 😅 .

Even better it depends from this value :
```
cat ~/.config/gcloud/configurations/config_default
[core]
pass_credentials_to_gsutil = IfImFalseEverythingSucks
```

One of the approach could be that we check if this file is present and if this value is true and add the hotword to the list dynamically.

What happens if the file isn't there?

**Comment by romkatv** [comment]
What prompted you send this PR in the first place? Do you have a use case where you run a specific `gsutil` command and want to see the content of `~/.config/gcloud/active_config` when you do so?

**Comment by thekoma** [comment]
Hi @romkatv it is useful as gsutil has autocomplete and auto complete and doble tabbing will list your buckets.
So knowing in which project you are is helpful.
As I said it is part of the gcloud suite so everything in it in some way act with `~/.config/gcloud/active_config` as default.

**Comment by romkatv** [comment]
If it's useful to you, then it must make sense. Merged. Thanks for your patience in this one.

**Pull request merged**
