### PR TITLE
Towards a working Linux wifi widget

### PR DESCRIPTION
**Pull request by sys-lectern**
Hey, thanks for your help from [https://github.com/romkatv/powerlevel10k/issues/958](https://github.com/romkatv/powerlevel10k/issues/958)!

I refactored the code to be able to be merged with yours. Syntactically I tried to keep it as similar as possible, although this version does use more local binaries like **cut**, **grep**, and **tr** than native zsh parsing/expansion patterns. However, I did take the time to make them as fast as possible by testing several thousand iterations with hyperfine.

Hopefully everything else that's important is covered by my comments, but let me know if you have any concerns/questions.

### CODE REVIEW

**Comment by romkatv** [comment]
I don't have access to a Linux box with wifi. I have access to Android but this code doesn't work on Android.

Could you post the output of the following command?

```zsh
() {
  emulate -L zsh -o xtrace -o err_return
  command cat /proc/net/wireless
  command iw dev
  local dev=$(iw dev | grep 'Interface ' | cut -d\  -f2)
  command iw dev "$dev" link
  true
}
```

**Comment by sys-lectern** [comment]
Sure, no problem. Sorry, I copied the `(Linux|Android)` validator from another part of the code. This branch is not intended to work for Android.

Here's a potentially helpful resource with a couple more sample outputs under the **iw and wireless_tools comparison** section:
https://wiki.archlinux.org/index.php/Network_configuration/Wireless

**Also**, I made a couple of quick fixes/syntax improvements to the code.

### Here's sample output with wifi enabled:
```
+(anon):2> cat /proc/net/wireless
Inter-| sta-|   Quality        |   Discarded packets               | Missed | WE
 face | tus | link level noise |  nwid  crypt   frag  retry   misc | beacon | 22
wlp3s0: 0000   58.  -52.  -256        0      0      0      0     76        0
+(anon):3> iw dev
phy#0
	Unnamed/non-netdev interface
		wdev 0x9
		addr 5c:51:4f:18:4b:6b
		type P2P-device
		txpower 0.00 dBm
	Interface wlp3s0
		ifindex 2
		wdev 0x1
		addr 5c:51:4f:18:4b:6a
		ssid DailyGrindGuest1
		type managed
		channel 149 (5745 MHz), width: 40 MHz, center1: 5755 MHz
		txpower 22.00 dBm
		multicast TXQ:
			qsz-byt	qsz-pkt	flows	drops	marks	overlmt	hashcol	tx-bytes	tx-packets
			0	0	0	0	0	0	0	0		0
+(anon):4> iw dev
+(anon):4> grep '--color=auto' '--exclude-dir=.bzr' '--exclude-dir=CVS' '--exclude-dir=.git' '--exclude-dir=.hg' '--exclude-dir=.svn' '--exclude-dir=.idea' '--exclude-dir=.tox' 'Interface '
+(anon):4> cut '-d ' -f2
+(anon):4> local dev=wlp3s0
+(anon):5> iw dev wlp3s0 link
Connected to 74:83:c2:be:76:da (on wlp3s0)
	SSID: DailyGrindGuest1
	freq: 5745
	RX: 35192066 bytes (27041 packets)
	TX: 4090471 bytes (24287 packets)
	signal: -52 dBm
	rx bitrate: 243.0 MBit/s VHT-MCS 6 40MHz VHT-NSS 2
	tx bitrate: 240.0 MBit/s VHT-MCS 5 40MHz short GI VHT-NSS 2

	bss flags:	short-slot-time
	dtim period:	1
	beacon int:	100
+(anon):6> true
```

### And sample output with wifi disabled:
```
+(anon):2> cat /proc/net/wireless
Inter-| sta-|   Quality        |   Discarded packets               | Missed | WE
 face | tus | link level noise |  nwid  crypt   frag  retry   misc | beacon | 22
+(anon):3> iw dev
phy#0
	Interface wlp3s0
		ifindex 2
		wdev 0x1
		addr 5c:51:4f:18:4b:6a
		type managed
		txpower 22.00 dBm
		multicast TXQ:
			qsz-byt	qsz-pkt	flows	drops	marks	overlmt	hashcol	tx-bytes	tx-packets
			0	0	0	0	0	0	0	0		0
+(anon):4> iw dev
+(anon):4> grep '--color=auto' '--exclude-dir=.bzr' '--exclude-dir=CVS' '--exclude-dir=.git' '--exclude-dir=.hg' '--exclude-dir=.svn' '--exclude-dir=.idea' '--exclude-dir=.tox' 'Interface '
+(anon):4> cut '-d ' -f2
+(anon):4> local dev=wlp3s0
+(anon):5> iw dev wlp3s0 link
Not connected.
+(anon):6> true
```

**Comment by sys-lectern** [comment]
Also, ironically the only linux distribution which I tested that _didn't_ have **iw** installed by default was Arch Linux, but this is not surprising since it's very much a build-it-from-scratch distro. The package is available in the standard repositories for install.

**Comment by romkatv** [comment]
Thanks! Merged.

I've made a few changes but cannot test them due to the lack of access to appropriate hardware. Could you update powerlevel10k and verify that `wifi` segment works on Linux?

**Comment by sys-lectern** [comment]
Great! I'll update later today, check the diffs and do some testing

**Comment by romkatv** [comment]
> Great! I'll update later today, check the diffs and do some testing

Have you tried it? Does it work?

**Pull request merged**
